moby/tool

- Makefile
`gofmt`, `golint`, `go vet` - can add more like `ineffassign` as well but those would require `go get` and probably would make us want to use the linuxkit `go-compile`.  Figured it would be best to keep this separate.
Taken from notary.
> Add standard lint tools to Makefile

- cmd/moby/image.go
Due to a missing else the tool would previously terminate with an error
message showing that the kernel or init image didn't exist, even if it
was pulled successfully. Invoking the tool again would continue to the
next image.
Signed-off-by: Magnus Skjegstad <magnus@skjegstad.com>
> Don't exit after pulling init or kernel image without -pull

- cmd/moby/build.go
- cmd/moby/config.go
- cmd/moby/output.go
- cmd/moby/schema.go
- vendor.conf
- vendor/github.com/linuxkit/linuxkit/src/initrd/initrd.go
In order to test this better, added support for symlinks in `files` section and made the output quieter if you dont use sections.
See https://github.com/linuxkit/linuxkit/issues/1792
> Fix symlinks handling in initramfs

- cmd/moby/docker.go
- cmd/moby/output.go
Uses Docker API to replicate `docker run`, including the fallback to pull an image if it isn't found. Many thanks to @cpuguy83 for helping navigate the stdin/stdout codepaths, please let me know if this can be cleaned up further!  In particular I'm not thrilled about how I have to convert `input` into a file for stdin
Also removed unused `dockerRun` function.
Tested locally with a `moby build` and `linuxkit run` on `linuxkit.yml`
> Use Docker API for run

- cmd/moby/docker.go
- cmd/moby/image.go
cc @riyaz this isnt very well documented but if you ignore the `io.Reader` returned by `ImagePull` the connection will be closed before the pull happens.
I answered the relevant Stack Overflow question... http://stackoverflow.com/questions/42816132/docker-run-using-golang-api-docker-docs/43937375#43937375
> Fix docker pull

- Makefile
- circle.yml
- test/test.yml
This adds a very simple `make test` target that we can hook into a CI system like circle/travis/jenkins/(your favorite system here).
At present, the test does the following:
- runs golang linters
- compiles moby tool
- clones the linuxkit repo for a sample yml
- builds the sample `linuxkit.yml`
I've added a sample `circle.yml` file but because I am not an admin for this repo/org I can't hook it up/test it.
This test can (and should) be factored out into a more full-featured suite and include golang unit tests, but I wanted a quick smoke test that we could start enforcing against PRs in the short term to get this going.
> Simple test target

- Makefile
- cmd/moby/build.go
- cmd/moby/config.go
- cmd/moby/config_test.go
- cmd/moby/output.go
Using the label `org.mobyproject.config` will use that JSON
(or yaml, but it is very hard to get yaml into a label as newlines are
not respected) for parameters that are not explicitly set in the yaml file.
Had to change parameter definitions so override behaves as expected.
fix #16
> Add support for override of parameters using a label

- cmd/moby/config.go
- cmd/moby/schema.go
This PR proposes adding the `source` attribute to the `file` struct.
When preparing an image bundling `dockerd`, we usually embed the generated server certificate and key (`server.pem` and `server-key.pem`) to the image for fast deployment. This `source` attribute allows us to copy the content of these files into the image.  
Signed-off-by: Chanwit Kaewkasi <chanwit@gmail.com>
> add Source attribute to File

- Makefile
- cmd/moby/build.go
- cmd/moby/config.go
- cmd/moby/config_test.go
- cmd/moby/output.go
- cmd/moby/schema.go
- test/test.yml
This removes outputs from yaml, instead you can do
```
moby build -output tar -output qcow2 file.yaml
```
or alternative syntax
```
moby build -output tar,qcow2 file.yaml
```
In future we may change this to be available in a `moby package`
step, but lets try this for now.
> Remove output formats from the Yaml file, put in CLI

- .gitignore
> Fix gitignore to not ignore moby directory

- cmd/moby/build.go
Remove unnecessary argument to buildInternal function, does not need to know the name.
> Fix build in directory

- cmd/moby/trust.go
This dir is where you'd place private keys for signing but this is irrelevant for build.  Also where the moby tool pulls down metadata from the server, but this can be removed - we could cache it in a canonical moby tool directory like docker (`~/.docker`) and notary (`~/.notary`) do, if we'd like to in the future.
> trust: use a tempdir and remove after build

- cmd/moby/config.go
From [the docs](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems), `rbind` is not an option in the docker command line, but always seems to be applied by the daemon (code [here](https://github.com/moby/moby/blob/master/daemon/oci_linux.go#L553-L561) and [here](https://github.com/moby/moby/blob/103f2e56bf753019a4013a2722f908a3ee1bc558/daemon/volumes_unix.go#L195 
)). Do the same for the moby tool itself.
> Always include rbind in user-specified volume options

- cmd/moby/docker.go
- test/test.yml
Currently there's a bug with how content trust is handled because the image reference becomes more specific from the notary lookup and we lose the tag.  DCT manually retags the image after pull, so do the same here on a best-effort basis. This manifests itself only on the `init` images because it's only exercised in that codepath of `ImageExtract`.
This should fix the CI failures in https://github.com/linuxkit/linuxkit/pull/1913 -- I didn't reproduce the CI failures at first because of caching but I was able to reproduce and verify the fix. 
Also bumps the test yml to test trust more thoroughly, and use the new labels
> trust: always tag after pull

- cmd/moby/build.go
Implements the `-disable-content-trust` flag with a default `false` value.  Closes https://github.com/moby/tool/issues/55
> add disable-content-trust flag for one-off build

- cmd/moby/build.go
- cmd/moby/trust_test.go
- test/test.yml
- the smart tag/digest chopping logic had a bug, included a fix and unit tests - I intend to add more unit tests for other parts of the trust code.
- I split out the vendoring commit: related to our discussion in slack, there were other changes for other packages.  I deleted the `/vendor` directory and revendored with `vndr`
- also added smarter Org parsing logic to allow for `library` to be specifiable to perform trust checks on official images
> trust: parsing fixes and tests

- cmd/moby/build.go
- cmd/moby/output.go
With the new build output command, it's possible to have a typo in the desired output, that doesn't get validated till all of the building/pulling is about done.
This validates the build output prior to doing any work.
> Validate output before doing the work

- cmd/moby/trust.go
As discussed on the linuxkit community slack, introduce a `~/.moby/trust` by default directory on the host intended for caching important trust data and/or future configuration. 
```
🐳 $ moby --help
<..snip..>
Options:
-d string
Configuration directory (default /Users/riyaz/.moby)
```
This will optimize notary lookups since if we determine we have the most up-to-date trust data cached we don't need to request as much data from the notary server. Also provides security benefits since we pin local metadata and prevent version rollback.
> add default trust config and cache dir

- cmd/moby/build.go
- cmd/moby/linuxkit.go
- cmd/moby/output.go
- does not require docker if user has qemu natively, will still fall back to docker
- allow specifying size for fixed size disk images
- add a raw disk output format
- more dogfooding
- marginally slower, but can be improved later
> Use linuxkit to build qcow2 and raw image disks, rather than docker containers with libguestfs

- cmd/moby/linuxkit.go
- cmd/moby/main.go
- cmd/moby/output.go
qemu calls in a container use `-v` with a single path from the image so
other resources must be under this.
> Add the temporary directories under ~/.moby

- cmd/moby/build.go
- cmd/moby/config.go
- cmd/moby/docker.go
- cmd/moby/image.go
- cmd/moby/trust.go
- When using `trust`: check the local image cache for the newly translated image reference before issuing a pull API request, unless force `-pull` was specified
- Fall back to local `trust` cache when offline, to enable offline trusted builds if local trust data already exists.  Note that notary library will output `warn` level log statements, which will be shown on output for the current default log level
- Remove an extraneous kernel pull, since this is already handled in the `imageTar` logic
- Only print `Pull image...` if we actually issue the API request to pull down remote data. Additionally, print the full reference of the image, which may be updated from content trust:
```
Extract kernel image: linuxkit/kernel:4.9.x
Pull image: …
```
> trust: check local image cache to not pull every time

- cmd/moby/build.go
- cmd/moby/config.go
Each section will be appended in order of the CLI, other then
kernel where last specified one wins.
This is useful if you eg want to have a base version for (say)
AWS and GCP and then add your own image on top.
> Allow specification of multiple yaml files for a single build

- cmd/moby/build.go
- cmd/moby/config.go
- cmd/moby/image.go
- cmd/moby/linuxkit.go
- cmd/moby/output.go
The `tar` output format (and others to come) will now output using streaming rather than buffering everything up. Allow them to be output to `stdout` and files in a streaming fashion. This should save a lot of memory on large outputs.
eg you can see list of generated files with
```
moby -q build -output tar -o - linuxkit.yml | tar tf -
```
The LinuxKit disk outputs can't do this, as they have to construct whole disks. So there are two kinds of output. We will probably split these into "build" and "package" later. Most of the host outputs will probably be the streaming type and the LinuxKit ones not.
Haven't changed the CLI to some sort of "package" method as haven't worked out a nice design thats not too verbose yet.
> Use streaming output where possible

- cmd/moby/build.go
- cmd/moby/linuxkit.go
- examples/README.md
- examples/docker.yml
- examples/linuxkit.yml
- examples/nginx.yml
- pkg/init-container/Dockerfile
- pkg/init-container/Makefile
- pkg/init-container/bin/rc.init
- pkg/init-container/etc/init.d/010-containerd
This is first prototype for running images on the host. Next comes `systemd`, `deb` and `rpm`.
```
moby build -output docker -o - docker.yml nginx.yml | docker build -t dockertest -
docker run -d -p 80:80 --privileged dockertest
moby build -output kernel+initrd linuxkit.yml nginx.yml
linuxkit run nginx
```
Both of these will run the same `nginx` either in a VM or a container.
(note `--privileged` is required as we are running `containerd` and `runc` in the Docker container still, so they need to be able to do mounts etc. Also `runc` is excessive in the permissions it requires).
> Add an output format for running images with Docker

- cmd/moby/output.go
Make `raw` output type call its file `.raw` as well, other minor fixes.
> Fixes for output types

- cmd/moby/build.go
- cmd/moby/config.go
- cmd/moby/schema.go
Also keep track of directory creation there, so you can explicitly
set directory permissions if required, and to avoid duplicates.
We should really keep track of files created elsewhere in the build
as well as we still might create some extras, but at least you can
set the write permisisons.
We can add uid, gid support too if required...
cc @deitch you asked for this...
> Allow setting of mode in files section

- cmd/moby/build.go
tarballs should only have relative paths in.
> Remove absolute paths from files

- cmd/moby/build.go
> Allow ~ for home directory when specifying source of file

- cmd/moby/build.go
For example you can do
```
moby build https://raw.githubusercontent.com/linuxkit/linuxkit/master/linuxkit.yml
```
> Add support to fetch yaml file with http

- cmd/moby/image.go
This disables the code in LinuxKit's `/bin/rc.init` which attempts to detect an
unconfigured hostname and generate a unique (ish) version from the MAC address.
Anyone who wants a specific fallback hostname can populate `etc/hostname`
through the `files` stanza in their `yml` file.
Signed-off-by: Ian Campbell <ian.campbell@docker.com>
> Do not force default hostname `moby`.

- cmd/moby/build.go
- cmd/moby/linuxkit.go
- enable the hyperkit option by default on MacOS
- use it for creating raw disk images
fix #68
> Use hyperkit to make raw disks

- cmd/moby/build.go
- cmd/moby/config.go
- test/test.yml
- change to a pointer type so we can distinguish empty from unset.
> Allow creation of empty files

- src/moby/config.go
- src/moby/config_test.go
Finally got around to looking at this too.
Rather than build the image and have something weird happen, let's check that the capabilities specified are actually valid capabilities.
> check that caps are valid

- src/moby/output.go
Adding support for the dynamic-vhd output format.
Signed-off-by: Dave Freitag <dcfreita@us.ibm.com>
> Adding 'dynamic-vhd' Output Format

- src/moby/build.go
- src/moby/config.go
- src/moby/schema.go
Allow setting ambient capabilities, as a seperate option to the standard
ones. If you are running as a non root user you should use these.
Note that unless you add `CAP_DAC_OVERRIDE` and similar permissions you
need to be careful about file ownership. Added support to set ownership
in the `files` section to help out with this.
> Add support for ambient capabilities

- docs/yaml.md
- src/moby/build.go
- src/moby/config.go
- src/moby/config_test.go
- src/moby/schema.go
In order to support not running containers as root, allocate
each of them a uid and gid, a bit like traditional Unix system
service IDs. These can be referred to elsewhere by the name of
the container, eg if you wish to create a file owned by a
particular esrvice.
> Assign each container a uid and gid it can use

- cmd/moby/build.go
- src/moby/config.go
Continue to allow onboot to have duplicates as we do not run simultaneously
so that is ok (and we number them anyway), but services are run together
so we will get a runtime error if duplicated as this is the containerd/runc
id.
(note in future we may change to using a hash not a list for these, but `append` could
still error so we will still need a check).
cc @deitcher
> Error if there are duplicate service names

- src/moby/linuxkit.go
This updates to the current set of images as of
https://github.com/linuxkit/linuxkit/pull/2159
> Update LinuxKit components used for build

- Makefile
- circle.yml
This removes the `lint` dependency from the moby target.
I've also added ineffassign to check ineffecutal assignments alongside
checks to ensure that both it and golint are installed before using it!
Note: [Tests](https://travis-ci.org/dave-tucker/homebrew-linuxkit/builds/253523307) in `hombrew-linuxkit`
shows many counts of `find: golint: No such file or directory` when golint isn't installed.
This could be an indication that we have a deeper issue with the golint runes.
- `make` builds `moby`
- `make test` lints, builds moby and runs the tests.
- `make lint moby` will lint and then builds moby
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>
> Makefile: Update for ease of Homebrew installation

- docs/yaml.md
- src/moby/build.go
- src/moby/config.go
- src/moby/schema.go
fix #113
Use `tar: none` or `tar: ""` to omit the tarball.
> Allow specifying the kernel and tarball names, or omitting tarball

- docs/yaml.md
- src/moby/config.go
- src/moby/config_test.go
- src/moby/schema.go
Previously I was forcing them to be strings, which is horrible. Now you
can either specify a numeric uid or the name of a service to use the
allocated id for that service.
> Allow uid, gid fields to be numeric or names

- src/moby/trust.go
Passing a `nil` pool will automatically use the system pool, even on Windows.  I tested locally with an empty trust cache.
Closes #119 
> trust: do not call x509.SystemCertPool as nil will use this as default

- docs/yaml.md
- src/moby/build.go
- src/moby/config.go
- src/moby/schema.go
- test/test.yml
Currently this supports "yaml" as the only option, which will output the yaml config (as JSON) into the file specified in the image.
Fix #107
This should be extended to add more metadata, eg moby tool commit and version used to build, and anything else useful.
> Add a "metadata" file contents flag

- src/moby/config.go
Otherwise JSON output as metadata cannot actually be used as it
has capitalised field names.
> Add json config for top level config

- docs/yaml.md
- src/moby/build.go
- src/moby/config.go
- src/moby/schema.go
- test/test.yml
This is a list of images to run on a clean shutdown. Note that you must not rely on these
being run at all, as machines may be be powered off or shut down without having time to run
these scripts. If you add anything here you should test both in the case where they are
run and when they are not. Most systems are likely to be "crash only" and not have any setup here,
but you can attempt to deregister cleanly from a network service here, rather than relying
on timeouts, for example.
Fix https://github.com/linuxkit/linuxkit/issues/1988
Corresponding PR for LinuxKit coming once this is merged.
> Add support for onshutdown

- src/moby/image.go
This is to clean up how we do writeable containers in LinuxKit.
> Add a tmp directory for each container to be used as a mount point

- src/moby/build.go
- src/moby/image.go
To work with truly immutable filesystems, rather than ones
we sneakily remount `rw`, we are going to use overlay for
writeable containers. To leave the final mount as `rootfs`,
in the writeable case we make a new `lower` path for the read
only filesystem, and leave `rootfs` as a mount point for an
overlay, with the writable layer and workdir mounted as a tmpfs
on `tmp`.
See https://github.com/linuxkit/linuxkit/issues/2288
> Rework setup of container for read only/read write

- src/moby/build.go
- src/moby/config.go
Also do some code cleanup.
Related to #131 we need to read the OCI config to find if the container
is read only, not rely on the yaml, as it may just be set in the label.
> Fix read only output when defined in a label

- src/initrd/initrd.go
- src/moby/image.go
When we converted these to cpio we were not noticing that they
were invalid as they had incorrect paths as we converted the
path to a symlink anyway. Only the busybox images have hard links
in, the Alpine ones are symlinks anyway, which is why it was
less visible too.
> Fix hardlinks in tar output

- src/moby/output.go
The image is multi-arch and should work on arm64 as it has no boot loader...
> Output EFI ISO as for BIOS ISO with filesystem on.

- docs/yaml.md
- src/moby/config.go
- src/moby/schema.go
- test/test.yml
This adds all the cgroup restrictions into the spec.
Note that we have to move disable OOM killer, as it is now part of the Cgroup spec.
> Add Cgroup resource limits into Yaml spec

- src/moby/build.go
- src/moby/image.go
This will do the wrong thing on Windows, and construct paths with \.
fix #142
> Do not use filepath.Join if constructing LinuxKit paths

- docs/yaml.md
- src/moby/build.go
- src/moby/config.go
- src/moby/config_test.go
- src/moby/image.go
- src/moby/schema.go
This adds a `runtime` section in the config that can be used
to move network interfaces into a container, create directories,
and bind mount container namespaces into the filesystem.
See also https://github.com/linuxkit/linuxkit/pull/2413
> Add support for runtime configuration

- docs/yaml.md
- src/moby/build.go
- src/moby/config.go
- src/moby/image.go
- src/moby/schema.go
This could be used in LinuxKit now, as there are some examples, eg
https://github.com/linuxkit/linuxkit/blob/master/blueprints/docker-for-mac/base.yml#L33
which are creating containers to do a mount.
This now also uses these to generate the mounts needed for writeable containers, and also automatically de-dups containers that share the same image by using the same mount as the source.
> Add support for mount in runtime config

- Makefile
- cmd/moby/build.go
- examples/README.md
- src/moby/output.go
This was confusing as there is an option to output to a file as well.
cc @deitch I think you suggested this...
> Rename "output" to "format"

- docs/yaml.md
- src/moby/build.go
- correct the syntax of the documented example
- make it really produce yaml (and add the previous mode as "json" since that is what it was producing).
> Couple of minor updates to metadata file output

- cmd/moby/build.go
- src/moby/linuxkit.go
- src/moby/output.go
We are going to phase out the LinuxKit build option, in favour of keeping Docker
or a native Linux build option for CI use cases, as it is faster. So the
hyperkit option that only worked in one very limited use case is not needed.
> Remove the hyperkit option

- Makefile
- src/moby/docker.go
- src/moby/output.go
_(sorry for the blank PR, hit the button too soon)_
~~Merge after https://github.com/linuxkit/linuxkit/pull/2607 only.~~
This updates to the new set of `linuxkit/mkimage-*` updated by https://github.com/linuxkit/linuxkit/pull/2607 and arranges to use content trust on them instead of digests.
I also disabled network, since none of them should need it.
Lastly I updated the `Makefile` deps so the tool is rebuilt when needed.
> Update mkimage plus no docker network

- docs/yaml.md
The documentation is a little bit unclear regarding how `binds` works, I've added a note (got the same problem as [here](https://stackoverflow.com/questions/46545259/linuxkit-getty-getting-stuck) and spent too much time on this trivial issue that's obvious for moby developers, but not so obvious for the end users).
> Updated the documentation regarding binds options.

- src/moby/output.go
Looks like a6b89f113787 ("Update linuxkit/mkimage-*") updated to a
non-existing tag.
linuxkit pkg show-tag tools/mkimage-iso-bios
linuxkit/mkimage-iso-bios:165b051322578cb0c2a4f16253b20f7d2797a502
and docker pull of that image works.
See https://github.com/linuxkit/linuxkit/pull/2612. Once this is merged I'll update the moby tool hash for Linuxkit as part of https://github.com/linuxkit/linuxkit/pull/2612
> Fix mkimage-iso-bios hash

- src/moby/build.go
Since #159 there is no more logging during the processing of init images. This PR adds it back :)
> Add back init image processing logging

- src/moby/output.go
Signed-off-by: Avi Deitcher <avi@deitcher.net>
this PR does the following:
* Add new output format: `raw-efi` - amd64 and arm64
* Add new output format `raw-bios` - amd64 only (BIOS doesn't exist on arm)
* Rename output format `raw` to `aws` 
* Rename output format `qcow2` to `qcow2-bios`
Reasonings as follows:
Didn't exist until now. Completes the [merged raw-efi linuxkit PR](https://github.com/linuxkit/linuxkit/pull/2540)
The existing "raw" format really created a large image (1GB) to comply with AWS requirements. It also was bios only, and therefore the name was confusing. It also required launching linuxkit and building in a VM.
This new format is minimal, per linuxkit philosophy, has a clear name, and builds using `docker run`. There is an intent to merge the functionality into moby …
> Add raw file formats, rename raw to aws and qcow2 to qcow2-bios

- src/moby/output.go
This is due to lack of rebase after linter changes.
> Fix some lint errors with error checking

- Makefile
Getting Homebrew to work with a GOPATH is horrible...
> Add a build target which works when GOPATH is not set or correct

- src/moby/output.go
Signed-off-by: Avi Deitcher <avi@deitcher.net>
Per @rn , previous PR did not adjust the prereq
> Fix prereqs in output.go

- .circleci/config.yml
I don't know why but the current arrangement seems to not be working, at least the two most recent master builds seem to lack them:
https://circleci.com/gh/moby/tool/292#artifacts/containers/0
https://circleci.com/gh/moby/tool/289#artifacts/containers/0
I can't see anything wrong with the existing file, but try perturbing it...
> Tweak circleci config to try and fix artifact upload

- docs/yaml.md
Solv: Updated documentation to point out limits of
files section regarding /var, /run, and /tmp dirs.
This attempts to update documentation due to https://github.com/linuxkit/linuxkit/issues/2711.
> Prob: Files section does not work for /var dir

- docs/yaml.md
- src/moby/config.go
- src/moby/schema.go
This will create the list of cgroups specified
Note that the implementation is not done yet in linuxkit...
> Add Cgroups to runtime config

- examples/README.md
This one fixes the example command producing a docker image to use the existing files and be consistent with the standard VM image.
Signed-off-by: Tobias Gesellchen <tobias@gesellix.de>
> Fix docker format build example

- src/moby/config.go
- src/moby/config_test.go
Where "config-related" here means "ones you might find in the
"org.mobyproject.config" label on an image.
By making this new struct an anonymous member of the existing Image struct the
Go json parser does the right thing (i.e. inlines into the parent) when parsing
a complete image (from a yml assembly) by default. The Go yaml library which we
use requires a tag on the anonymous field to achieve the same.
My use case here is moving the `org.mobyproject.config` label definition out of the `Dockerfile` and into the `build.yml` consumed by `linuxkit pkg build`, which will be a PR to the linuxkit tool that'll I wil raise shortly. Splitting the `struct` like this avoids spurious empty `name` & `image` fields appearing in the label's content.
> Split config-related fields of Image into a substruct.

- cmd/moby/build.go
- cmd/moby/main.go
- src/moby/docker.go
- src/moby/image.go
- src/moby/linuxkit.go
- src/moby/output.go
Replacing a few uses of `bytes.Buffer` with temporary files or passing around `io.Reader` instead of a full buffer reduces the Maximum RSS (measured by `time(1)`) from 6.7G to 110M when building the `kube-master.iso` from https://github.com/linuxkit/kubernetes.
Motivation for looking into this was that in the https://github.com/linuxkit/kubernetes CI the image build process is occasionally being SIGKILL'd, since the CI containers are limited to 4G I hypothesised that the process was being OOM killed (I have not yet tested with these changes in place).
Since i have plenty of RAM no my test system the data, presumably, remains hot in the page cache so elapsed wallclock time is unaffected (it's a few seconds faster on a minute long build, so in the noise). On a memory (but not disk) …
> Reduce maximum memory usage via tempfiles

- src/moby/image.go
This was introduced by #191 but somehow did not trigger either for me in local
testing or in CI.
It did trigger in initial CI of https://github.com/linuxkit/linuxkit/pull/2811
which can be seen at https://linuxkit.datakit.ci/linuxkit/linuxkit/pr/2811?history=1637690296123e9a15307b3a41b290da6e27e7cc
The error is:
Failed to docker rm container «...»: «...»: aufs: unmount error after retries: «...»: device or resource busy
No doubt because we were still holding an open fd while trying to remove the
container.
Unclear why this didn't repro for me (docker 17.11.0-ce with overlay2) or
whatever CI uses.
> Defer dockerRm until we are finished with the contents

- src/moby/config.go
Signed-off-by: Robin Winkelewski <w9ncontact@gmail.com>
Add omitempty to yml declaration to enable marshalling valid yml.
Needed by linuxkit/linuxkit#2648
> add omitempty for yml config

- src/moby/config.go
Signed-off-by: Robin Winkelewski <w9ncontact@gmail.com>
if `inspect.Config` is nil there will be nil pointer exception [here](https://github.com/w9n/tool/blob/f4f714f2446faa4f8fb859ae673f29d13ff2bc8a/src/moby/config.go#L726).
> allow ImageInspect.Config to be nil when parsing

- docs/yaml.md
- src/initrd/initrd.go
- src/moby/build.go
- src/moby/config.go
- src/moby/linuxkit.go
- src/moby/output.go
- src/moby/schema.go
https://github.com/linuxkit/linuxkit/pull/2858 adds the Intel CPU ucode for all CPUs to the kernel package as `intel-ucode.cpio`. It is a cpio archive which needs to be prepended to the intrd (or if the booloader supports specifying multiple initrds it must be listed as the first).
This PR then adds:
- a new `ucode` option to the kernel section of the YAML to specify the cpio archive containing the ucode.
- adds the specified ucode as `/boot/ucode.cpio` in the intermediate tar ball
- extracts the ucode binary as part of the output phase
- prepends it to the initrd for `kernel+initrd` output
- adds it to the tar-kernel-initrd tarball
Som additional output formats, in particualr the raw disk and ISO variants should probably also get the support.
I've tested the resulting kernel+initrd files …
> Add support for Intel ucode

- Makefile
- docs/yaml.md
- src/moby/config.go
- src/moby/schema.go
- test/test.yml
Annotations do not do anything by default but get passed through to the runtime, which can be useful. I never metadata I didn't like...
Also fix sysctl to be a map in the validation, not an array. I can't see any examples using this in LinuxKit, but this matches OCI so is correct.
> Add support for OCI annotations in config

- docs/yaml.md
- src/moby/config.go
- src/moby/schema.go
This adds a namespace field to override the LinuxKit containerd
default namespace, in case you want to run a container in another
namespace.
Needs a patch in LinuxKit to implement this that I will open soon.
> Add support for setting containerd namespace in runtime config

- src/moby/output.go
> The vmdk and dynamic-vhd packages had a bug in them

- README.md
- docs/privateimages.md
As of right now, `moby build` (and by extension `linuxkit build`) do not read the executing user's docker credentials. This means that moby images cannot be composed of OCI images that require credentials to access, e.g. private images on a public registry like Docker Hub, or images on a private registry.
While there are plans to support credentials, this documentation change should enable people to know of the issue and work around it until such time as support is in place.
Signed-off-by: Avi Deitcher <avi@deitcher.net>
> Add documentation about using images from private registries

- src/moby/output.go
Signed-off-by: Garth Bushell <garth.bushell@oracle.com>
This builds on https://github.com/linuxkit/linuxkit/pull/2935 to enable building of qcow2 EFI images.
> Add qcow2 EFI image building support

- src/moby/output.go
We currently hardcode the Linuxkit/mkimage- images. This has the
unfortunate consequence that, if we update the LinuxKit image used
to generate the output, we have to update the Moby tool and then
vendor it back into the LinuxKit repository.
This commit introduces UpdateOutputImages() which allows a client
of the Moby tools package to selectively overwrite the packages
used to generate the outputs.
We keep the full image names (name + tag) intact in the source
to make it easier to update them with 'sed'. From the image names
we generate a map which can be updated with UpdateOutputImages().
See: https://github.com/moby/tool/pull/211#issuecomment-378893730
Signed-off-by: Rolf Neugebauer <rolf.neugebauer@gmail.com>
> Add ability to overwrite images used for outputs

- src/initrd/initrd.go
- src/moby/docker.go
- src/moby/output.go
This output produces a kernel and a root filesystem in squashfs format. squashfs is a read-only, compressed filesystem.
The 'kernel+squashfs' output can be used in a similar way as the default 'kernel+initrd' output format with the benefit that the rootfs does not consume any memory.
There is an additional commit which improves the logging for `dockerRun()`.
The `linuxkit/mkimage-squashfs` is already build and pushed.
> Add  'kernel+squashfs' output format

- .circleci/config.yml
We need the Format exptension in the tar package.
> Move to Go 1.10

- src/moby/build.go
- src/moby/image.go
- src/moby/output.go
The default Go tar has restrictions on filename length for example.
> Use PAX tar format
