moby/tool

LICENSE, NOTICE
=> Add license files

cmd/moby/build.go
e.g. `erb foo.yaml.rb | moby build -` produces `moby-bzImage` and so on
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
=> build: support reading yaml from stdin

cmd/moby/build.go, cmd/moby/output.go
This was too architecture specific previously.
=> Switch from bzImage to kernel for kernel image

cmd/moby/build.go, cmd/moby/image.go
`docker create` will not pull an image so we need an additional fallback.
Rework the pull and trust code so it is in one place to facilitate this.
=> Make sure we always pull images if create fails

cmd/moby/image.go
Noticed while I was implementing the `docker run` logic that we can check for the `image not found` error so we don't pull on every error.
Tested locally with `linuxkit.yml` - removed sysctl and did a successful `moby build`
=> Use IsErrNotFound to tighten err handling

cmd/moby/docker.go, cmd/moby/output.go
This reverts commit ec6fea1d679012b9633a476f337f6602c665dfe9.
Will re-add once https://github.com/moby/tool/pull/29 is in a good state, closes #28
=> Revert "Use Docker API for run"

cmd/moby/docker.go
=> Add missing import

cmd/moby/output.go
This is a fairly generic bootable disk with syslinux. Should
work if you dd it onto a USB stick, and should also work for AWS.
You need to uncompress it of course! Default size is 1G.
Will add cli option to set the size once I split out `moby build`
and `moby package` shortly.
=> Add a compressed disk image format

circle.yml
Try fixing circle, previous failure here: https://circleci.com/gh/moby/tool/1
=> Update working dir and get golint for circle tests

circle.yml
Unfortunately this took longer than expected because the documentation wasn't too verbose, but here's a green run: https://circleci.com/gh/riyazdf/tool/24
=> Fixup circle CI

cmd/moby/config.go
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
=> config: fix tmpfs parsing

cmd/moby/docker.go
I was working on #29 and realized we could also clean up by removing this unused functon
=> Remove docker run function as it is unused

cmd/moby/build.go
=> Add a -dir option for location of output files

cmd/moby/config.go
Default to sharing net, ipc, uts namespaces between containers in config.
This makes most sense, as this is normal other than if we want to specifically
isolate system containers, in which case we will specify in config.
- explicitly support the value "new" if you want to isolate
- support the synonym "root" for "host" as in non LinuxKit setups it may
not actually be the host, it will be the current namespace.
- only support "none" as a synonym for "new" for network namespace where it is
carried over from Docker.
=> Change the default namespaces

cmd/moby/main.go, cmd/moby/util_unix.go, cmd/moby/util_windows.go
=> Add a ~/.moby directory for config

cmd/moby/linuxkit.go, cmd/moby/output.go
GCP does not recognise them for unclear reasons.
=> Do not use Linuxkit to build GCP images for now

cmd/moby/output.go
- generally people refer to a plain disk image as `raw`
- `gcp` is shorter and it is the only image type supported
- remove `img-gz` as it is not needed. It does not really save space
as you have to build the full image and compress it anyway. On
many platforms the `raw` image will be a sparse file anyway,
even on the Mac soon.
=> Rename img→raw and gcp-img→gcp

cmd/moby/build.go, cmd/moby/config.go, cmd/moby/schema.go, docs/yaml.md
See discussion in https://github.com/linuxkit/linuxkit/pull/2027
=> Allow some files specified with `source` to be optional

cmd/moby/config.go, cmd/moby/schema.go, docs/yaml.md
Use a microformat eg `nofile,100,200`. You can use `unlimited`
to set no limit.
Needed for https://github.com/linuxkit/linuxkit/issues/1852
=> Add support for rlimits

cmd/moby/build.go
This makes it easier to convert to a library.
=> Return errors from build internal function

cmd/moby/docker.go, cmd/moby/output.go
This is a remnant of when there were multiple versions.
=> Rename the docker run function

Makefile, cmd/moby/build.go, cmd/moby/main.go, src/moby/build.go, src/moby/config.go, src/moby/config_test.go, src/moby/docker.go, src/moby/image.go, src/moby/linuxkit.go, src/moby/output.go, src/moby/schema.go, src/moby/trust.go, src/moby/trust_test.go, src/moby/util.go, src/moby/util_unix.go, src/moby/util_windows.go
- this is pretty much the smallest change to split this out and it
exposes a few things that can be improved later
- no change to logging yet
=> Split out into a small stub command line and a library

docs/yaml.md
=> Add docs for ambient capabilities

docs/yaml.md, src/moby/config.go, src/moby/schema.go
This adds the OCI parts needed into the yaml, but there are still
permissions issues in practise so marked as experimental.
It may just need further documentation to resolve the issues.
=> Add partial user namespace support

src/moby/CONTRIBUTING.md
=> Add Contributing doc

src/moby/build.go, src/moby/image.go
Unfortunately there are a lot of issues with resolv.conf as we
cannot actually write it into the image from any docker image, as docker will
always have something bind mounted in.
In addition, normally we expect the filesystem to br read only for images
that moby generates, so the actual etc/resolv.conf is likely not to be writeable.
Previously we were adding in a default resolv.conf into every image pointing at
Google's name servers but that is really a bad idea.
Instead, normal images now get an empty default, while images in the `init`
section will get a symlink, currently hard coded to `/run/resolvconf/resolv.conf`
but you can override this with the `files` section to be static or a different
link.
In future, if we have an easy way to build and extract images with user control
of …
=> In the init section use a symlink for /etc/resolv.conf

src/moby/linuxkit.go
=> Update mkimage used for building to lastest hashes

src/moby/docker.go, src/moby/output.go
Rather than using an initrd, unpack full filesystem for ISO BIOS.
Stream docker output direct to file rather than via a buffer, to save
memory and improve performance.
See also https://github.com/linuxkit/linuxkit/pull/2339
=> Use new style ISO BIOS mkimage from Linuxkit which unpacks filesystem

examples/docker.yml, examples/linuxkit.yml, examples/nginx.yml, src/moby/build.go
With https://github.com/linuxkit/linuxkit/pull/2500 the init script
can be used for both bare metal and in Docker.
=> Used shared init with LinuxKit

src/moby/output.go
See https://github.com/linuxkit/linuxkit/pull/2524
=> Update to use new common iso EFI for amd64 and arm64

src/moby/config.go, src/moby/image.go
Previously any Runtime specified in yml would completely override anything from
the image label, even if they set distinct fields. This pushes the merging down
to the next layer, and in the case of BindNS down two layers.
Most of the fields involved needed to become pointers to support this, which
required a smattering of other changes to cope. As well as the local test suite
this has been put through the linuxkit test suite (as of cc200d296a94).
I also tested in the scenario which caused me to file #152.
Fixes #152.
=> More granular merge of Runtime from labels & yaml

src/moby/output.go
This is a tarball of the kernel, initrd and cmdline files, suitable for
sending to the mkimage images that expect this format.
Note you can't currently stream this output format using `-o` will clean this
up in future commits.
=> Add a "tar-kernel-initrd" output format

src/moby/output.go
The soon to be PRed `mkimage-rpi3` takes a tar ball of the filesystem and returns a tarball to be extracted on a FAT32 filesystem on a SD card. I've sucessfully booted a RPi3 with this.
I suggest we merge this first, then I can update the `moby` hash in `linuxkit` when I submit the rest of the patches.
=> output: Add support for creating Raspberry Pi images

src/moby/docker.go
This avoids https://github.com/docker/cli/issues/631
This is an alternative to #170.
=> Do an explicit docker pull before docker run.

Makefile
=> rm -rf for clean

src/moby/output.go
Update the hash value of EFI-* docker images
Signed-off-by: Dennis Chen <dennis.chen@arm.com>
=> EFI image hash value update

poule.yml
This adds a basic poule configuration for repo automation.
=> Initial poule config

Makefile
https://github.com/linuxkit/kubernetes/pull/1#issuecomment-345253075 lead to
https://circleci.com/gh/linuxkit/kubernetes/15
Cribbed the runes from my PR https://github.com/linuxkit/linuxkit/pull/2690
=> Build a static binary

Makefile
=> Stop make test from removing binary

src/moby/build.go
Fix issues in https://github.com/linuxkit/linuxkit/pull/2761
=> Create tmp dir in case required

vendor.conf, vendor/github.com/containerd/containerd/LICENSE.docs, vendor/github.com/containerd/containerd/README.md, vendor/github.com/containerd/containerd/vendor.conf, vendor/github.com/gogo/protobuf/README, vendor/github.com/gogo/protobuf/Readme.md, vendor/github.com/gogo/protobuf/proto/encode.go, vendor/github.com/gogo/protobuf/proto/lib.go, vendor/github.com/gogo/protobuf/proto/properties.go, vendor/github.com/gogo/protobuf/proto/text.go, vendor/github.com/gogo/protobuf/proto/text_parser.go, vendor/github.com/gogo/protobuf/protobuf/google/protobuf/any.proto, vendor/github.com/gogo/protobuf/protobuf/google/protobuf/compiler/plugin.proto, vendor/github.com/gogo/protobuf/protobuf/google/protobuf/descriptor.proto, vendor/github.com/gogo/protobuf/protobuf/google/protobuf/duration.proto, vendor/github.com/gogo/protobuf/protobuf/google/protobuf/empty.proto, vendor/github.com/gogo/protobuf/protobuf/google/protobuf/field_mask.proto, vendor/github.com/gogo/protobuf/protobuf/google/protobuf/struct.proto, vendor/github.com/gogo/protobuf/protobuf/google/protobuf/timestamp.proto, vendor/github.com/gogo/protobuf/protobuf/google/protobuf/wrappers.proto
Since that bumps to gogo protobuf v0.5 too do the same.
Note that there are no actual containerd changes here, although there are some
gogo proto ones.
=> Bump to containerd v1.0.0

src/moby/image.go
User specified mounts should be able to rely on the rootfs being mounted, in
particular for a writeable container they should expect the writeable overlay
to already be in place.
=> Prepend the rootfs mounts to the user specified runtime.mounts.

src/moby/linuxkit.go, src/moby/output.go
=> Update LinuxKit images to the latest

src/moby/output.go
=> Update mkimage images based on linuxkit/alpine to latest.
